### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by Thomsonjaved** [socketio/socket.io-client-java#697] opened 2022-01-01 11:56 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by darrachequesne** [comment] 2022-01-01 22:39
Duplicate of https://github.com/socketio/socket.io/issues/4232.

**Closed by darrachequesne** 2022-01-01 22:39 UTC
Labels: enhancement
