### ISSUE TITLE
de-couple json framework from the client

### ISSUE THREAD

**Issue by emaayan** [socketio/socket.io-client-java#499] opened 2018-02-04 13:02 UTC
in the event the calling application already uses json framwork on it's own, it should be allowed to continue using it and not be coupled to json library that comes with it.

**Comment by darrachequesne** [comment] 2022-06-30 10:41
Duplicate of https://github.com/socketio/socket.io-client-java/issues/235

**Closed by darrachequesne** 2022-06-30 10:41 UTC
