### ISSUE TITLE
OkHttp connections do not seem to be closed

### ISSUE THREAD

**Issue by sandro-csimas** [socketio/socket.io-client-java#275] opened 2016-01-26 17:52 UTC
My application show the follow log:
````
01-26 14:32:47.975 14396-16699/com.closic W/OkHttpClient: A connection to https://localhost:3101/ was leaked. Did you forget to close a response body?
````
3101 is the Socket.io port. Can you check if all connections are closed?

**Comment by nkzawa** [comment] 2016-01-29 16:27
Thanks for your report !!

Maybe we'd have to close `response.body()` of `onOpen` ? cc @b95505017

https://github.com/socketio/engine.io-client-java/blob/master/src/main/java/io/socket/engineio/client/transports/WebSocket.java#L78

**Comment by b95505017** [comment] 2016-01-29 17:07
Not sure what that Response is for. I didn't see they close it in the sample guide.
https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/WebSocketEcho.java
Need time to figure it out, or file an issue to them.

**Comment by sandro-csimas** [comment] 2016-01-29 19:01
https://github.com/square/okhttp/issues/2158
I think calling response.body().string() closes the connection if its the case.

**Comment by b95505017** [comment] 2016-01-30 02:30
@sandro-csimas How did you reproduce this issue?

**Comment by sandro-csimas** [comment] 2016-01-31 00:03
I just started my Android app.
I'm using socket.io-client-0.6.3.
````
private void setupSocket() {
  options = new IO.Options();
  options.secure = true;
  options.forceNew = false;
  try {
    socket = IO.socket(Configuration.IO_URL, options);
  } catch(URISyntaxException e) {
    Log.e(TAG, "Error creating socket instance", e);
    throw new APIException(e);
  }
}
````
````
public synchronized void connect(User user) {
  options.query = "user=" + user.getId();
  socket.connect();
  enableEvents();
}
````

**Comment by ronenab** [comment] 2016-02-08 10:52
is this connected?
http://stackoverflow.com/questions/35267061/socket-io-okhttp-exception

**Comment by berkayturanci** [comment] 2016-03-21 07:54
Is there a progress about this?

This may help;

java.lang.IllegalStateException: must call close()
at okhttp3.internal.ws.RealWebSocket.sendMessage(RealWebSocket.java:108)
at io.socket.engineio.client.transports.WebSocket$3.call(WebSocket.java:173)
at io.socket.engineio.parser.Parser.encodePacket(Parser.java:63)
at io.socket.engineio.parser.Parser.encodePacket(Parser.java:42)
at io.socket.engineio.client.transports.WebSocket.write(WebSocket.java:168)
at io.socket.engineio.client.Transport$3.run(Transport.java:101)
at io.socket.thread.EventThread.exec(EventThread.java:50)
at io.socket.engineio.client.Transport.send(Transport.java:96)
at io.socket.engineio.client.Socket.flush(Socket.java:608)
at io.socket.engineio.client.Socket.onDrain(Socket.java:599)
at io.socket.engineio.client.Socket.access$1000(Socket.java:30)
at io.socket.engineio.client.Socket$6.call(Socket.java:294)
at io.socket.emitter.Emitter.emit(Emitter.java:117)
at io.socket.engineio.client.transports.WebSocket$2$1.run(WebSocket.java:160)
at io.socket.thread.EventThread$2.run(EventThread.java:75)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:838)

**Comment by juanxme** [comment] 2016-04-04 02:34
I have the same problem

**Comment by martelli** [comment] 2016-04-27 23:19
I just had 2 occurences of the same stacktrace @berkayturanci posted.

**Comment by parkjaeiek** [comment] 2016-05-02 08:10
same problem

**Comment by johnmc5810** [comment] 2016-05-10 23:23
Same issue, any update on this-cheers :)

**Comment by bartlaarhoven** [comment] 2016-05-11 07:22
+1

**Comment by yadler** [comment] 2016-05-11 08:03
I've got the same issue (esp. during unit tests against wiremock)

**Comment by johnmc5810** [comment] 2016-05-11 12:31
Was seeing stack trace but java client was still sending messages but has since stopped sending messages, would this issue prevent the java client from sending messages? Java client is still connected

**Comment by jayrambhia** [comment] 2016-05-11 18:34
Getting daily crashes of more than 50 in production. I tried using try catch but nothing works. I'm stuck now.

**Comment by rubinbasha** [comment] 2016-05-13 11:14
Also have this issue , and it is really becoming a problem since I would like to at least have a place where to catch this so that it does not crash my app and kind of feel hopeless when confronted with it. Thinking of maybe injecting code in the library or something until there is a fix , but also do not know what and where exactly to inject.

**Comment by wilsonssss** [comment] 2016-06-12 05:54
anyone fix this problem?  
```
java.lang.IllegalStateException: must call close()
	at okhttp3.internal.ws.RealWebSocket.sendMessage(RealWebSocket.java:108)
	at io.socket.engineio.client.transports.WebSocket$3.call(WebSocket.java:173)
	at io.socket.engineio.parser.Parser.encodePacket(Parser.java:63)
	at io.socket.engineio.parser.Parser.encodePacket(Parser.java:42)
	at io.socket.engineio.client.transports.WebSocket.write(WebSocket.java:168)
	at io.socket.engineio.client.Transport$3.run(Transport.java:101)
	at io.socket.thread.EventThread.exec(EventThread.java:50)
	at io.socket.engineio.client.Transport.send(Transport.java:96)
	at io.socket.engineio.client.Socket.flush(Socket.java:608)
	at io.socket.engineio.client.Socket.sendPacket(Socket.java:695)
	at io.socket.engineio.client.Socket.sendPacket(Socket.java:672)
	at io.socket.engineio.client.Socket.access$100(Socket.java:30)
	at io.socket.engineio.client.Socket.access$402(Socket.java:30)
	at io.socket.engineio.client.Socket.access$500(Socket.java:30)
	at io.socket.engineio.client.Socket.access$600(Socket.java:30)
	at io.socket.engineio.client.Socket.access$800(Socket.java:30)
	at io.socket.engineio.client.Socket.access$900(Socket.java:30)
	at io.socket.engineio.client.Socket.access$1202(Socket.java:30)
	at io.socket.engineio.client.Socket.access$202(Socket.java:30)
	at io.socket.engineio.client.Socket.access$1400(Socket.java:30)
	at io.socket.engineio.client.Socket.access$1700(Socket.java:30)
	at io.socket.engineio.client.Socket.access$1800(Socket.java:30)
	at io.socket.engineio.client.Socket.access$1900(Socket.java:30)
	at io.socket.engineio.client.Socket$18.run(Socket.java:652)
	at io.socket.thread.EventThread.exec(EventThread.java:50)
	at io.socket.engineio.client.Socket.send(Socket.java:649)
	at io.socket.engineio.client.Socket.write(Socket.java:618)
	at io.socket.engineio.client.Socket.write(Socket.java:614)
	at io.socket.client.Manager$10.call(Manager.java:466)
	at io.socket.parser.Parser$Encoder.encode(Parser.java:86)
	at io.socket.client.Manager.packet(Manager.java:461)
	at io.socket.client.Socket.packet(Socket.java:264)
	at io.socket.client.Socket.access$300(Socket.java:19)
	at io.socket.client.Socket.access$1100(Socket.java:19)
	at io.socket.client.Socket$6.run(Socket.java:256)
	at io.socket.thread.EventThread$2.run(EventThread.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:831)
```

**Comment by johnmc5810** [comment] 2016-06-12 08:50
I tried 2 different ws libraries and still had issues connecting to the Amazon beanstalk server,seems to be a server issue rather than a issue with this library. I still need to investigate further though,what server deployments are you guys using?

**Comment by johnmc5810** [comment] 2016-06-14 08:15
It turned out to be a server issue when using aws beanstalk,library is now working great:-)

**Comment by KrawczykPawel** [comment] 2016-06-22 14:04
I have the same issue:

`
okhttp3.internal.ws.RealWebSocket.sendMessage (RealWebSocket.java:108)
io.socket.engineio.client.transports.WebSocket$3.call (WebSocket.java:175)
io.socket.engineio.parser.Parser.encodeByteArray (Parser.java:71)
io.socket.engineio.parser.Parser.encodePacket (Parser.java:51)
io.socket.engineio.parser.Parser.encodePacket (Parser.java:42)
io.socket.engineio.client.transports.WebSocket.write (WebSocket.java:168)
io.socket.engineio.client.Transport$3.run (Transport.java:101)
io.socket.thread.EventThread.exec (EventThread.java:50)
io.socket.engineio.client.Transport.send (Transport.java:96)
io.socket.engineio.client.Socket.flush (Socket.java:608)
io.socket.engineio.client.Socket.onDrain (Socket.java:599)
io.socket.engineio.client.Socket.access$1000 (Socket.java:30)
io.socket.engineio.client.Socket$6.call (Socket.java:294)
io.socket.emitter.Emitter.emit (Emitter.java:117)
io.socket.engineio.client.transports.WebSocket$2$1.run (WebSocket.java:160)
io.socket.thread.EventThread$2.run (EventThread.java:75)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.lang.Thread.run (Thread.java:818)`

**Comment by shobhitpuri** [comment] 2016-07-06 21:03
Thanks for looking into it. Any final solution to this issue ?

**Comment by eckovation** [comment] 2016-08-12 06:21
Any update on this? 
Thanks

**Comment by shobhitpuri** [comment] 2016-08-12 06:22
@eckovation If you find any please post it here. I've been trying to look for a long time. Thanks.

**Comment by EdwardClay** [comment] 2016-08-27 11:10
Problem still occurs at v0.7.0 as follows:

`java.lang.IllegalStateException: must call close() at okhttp3.internal.ws.RealWebSocket.sendMessage(RealWebSocket.java:108) at io.socket.engineio.client.transports.WebSocket$3.call(WebSocket.java:173) at io.socket.engineio.parser.Parser.encodePacket(Parser.java:63) at io.socket.engineio.parser.Parser.encodePacket(Parser.java:42) at io.socket.engineio.client.transports.WebSocket.write(WebSocket.java:168) at io.socket.engineio.client.Transport$3.run(Transport.java:101) at io.socket.thread.EventThread.exec(EventThread.java:50) at io.socket.engineio.client.Transport.send(Transport.java:96) at io.socket.engineio.client.Socket.flush(Socket.java:608) at io.socket.engineio.client.Socket.onDrain(Socket.java:599) at io.socket.engineio.client.Socket.access$1000(Socket.java:30) at io.socket.engineio.client.Socket$6.call(Socket.java:294) at io.socket.emitter.Emitter.emit(Emitter.java:117) at io.socket.engineio.client.transports.WebSocket$2$1.run(WebSocket.java:160) at io.socket.thread.EventThread$2.run(EventThread.java:75) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) at java.lang.Thread.run(Thread.java:818) `

**Comment by chendrak** [comment] 2016-08-27 15:10
@EdwardClay For a temporary workaround see [here](https://github.com/socketio/engine.io-client-java/pull/62#issuecomment-242122837)

**Closed** 2016-09-23 10:32 UTC

**Comment by nkzawa** [comment] 2016-09-23 10:33
Released 0.8.0. Feel free to reopen the issue if you still have the problem.

**Comment by EdwardClay** [comment] 2016-09-27 16:15
@nkzawa I got the following error with the version 0.8.0:

`java.lang.NullPointerException: Attempt to invoke virtual method 'io.socket.emitter.Emitter io.socket.emitter.Emitter.once(java.lang.String, io.socket.emitter.Emitter$Listener)' on a null object reference at io.socket.engineio.client.Socket$7.call(Socket.java:346) at io.socket.emitter.Emitter$OnceListener.call(Emitter.java:164) at io.socket.emitter.Emitter.emit(Emitter.java:117) at io.socket.engineio.client.Transport.onOpen(Transport.java:122) at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:28) at io.socket.engineio.client.transports.WebSocket$2$1.run(WebSocket.java:93) at io.socket.thread.EventThread$2.run(EventThread.java:80) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) at java.lang.Thread.run(Thread.java:818) `

**Comment by IlyaDiallo** [comment] 2016-09-27 17:03
@EdwardClay there's a fix: https://github.com/socketio/engine.io-client-java/pull/69/commits/1e72b45077460df0669b8ca63b4a1e68a378e1a6

See 0.8.1 release

**Comment by EdwardClay** [comment] 2016-09-27 17:09
@IlyaDiallo Oh, I see. Thank you.

**Comment by lpf870826** [comment] 2016-10-11 02:29
@nkzawa  @IlyaDiallo I got the following error with the version 0.8.0 / 0.8.1:

java.lang.NullPointerException
	at okhttp3.internal.tls.TrustRootIndex$BasicTrustRootIndex.<init>(TrustRootIndex.java:90)
	at okhttp3.internal.tls.TrustRootIndex.get(TrustRootIndex.java:48)
	at okhttp3.internal.tls.TrustRootIndex.get(TrustRootIndex.java:43)
	at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.java:147)
	at okhttp3.internal.platform.AndroidPlatform.buildCertificateChainCleaner(AndroidPlatform.java:159)
	at okhttp3.internal.tls.CertificateChainCleaner.get(CertificateChainCleaner.java:41)
	at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:602)
	at io.socket.engineio.client.transports.WebSocket.doOpen(WebSocket.java:55)
	at io.socket.engineio.client.Transport$1.run(Transport.java:82)
	at io.socket.thread.EventThread.exec(EventThread.java:55)
	at io.socket.engineio.client.Transport.open(Transport.java:77)
	at io.socket.engineio.client.Socket$2.run(Socket.java:248)
	at io.socket.thread.EventThread.exec(EventThread.java:55)
	at io.socket.engineio.client.Socket.open(Socket.java:226)
	at io.socket.client.Manager$1.run(Manager.java:330)
	at io.socket.thread.EventThread.exec(EventThread.java:55)
	at io.socket.client.Manager.open(Manager.java:250)
	at io.socket.client.Manager.open(Manager.java:240)
	at io.socket.client.Socket$3.run(Socket.java:133)
	at io.socket.thread.EventThread$2.run(EventThread.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)


Thanks!!!

**Comment by lpf870826** [comment] 2016-10-24 03:29
Sorry, The error is because my code 
new X509TrustManager() {
            @Override
            public X509Certificate[] getAcceptedIssuers() {
                return null;
            }

            @Override
            public void checkServerTrusted( X509Certificate[] chain, String authType )
                    throws CertificateException {
            }

            @Override
            public void checkClientTrusted( X509Certificate[] chain, String authType )
                    throws CertificateException {

            }
        } 


When i write it
            @Override
            public X509Certificate[] getAcceptedIssuers() {
                return new X509Certificate[0];
            }

the error is null;

Sorry.

**Comment by juanxme** [comment] 2016-11-21 16:10
Same issue v0.8.2

compile('io.socket:socket.io-client:0.8.2') {
        exclude group: 'org.json', module: 'json'
}

Fatal Exception: java.lang.IllegalStateException: closed
       at okhttp3.internal.ws.RealWebSocket.sendMessage(RealWebSocket.java:107)
       at io.socket.engineio.client.transports.WebSocket$4.call(WebSocket.java:189)
       at io.socket.engineio.parser.Parser.encodePacket(Parser.java:63)
       at io.socket.engineio.parser.Parser.encodePacket(Parser.java:42)
       at io.socket.engineio.client.transports.WebSocket.write(WebSocket.java:184)
       at io.socket.engineio.client.Transport$3.run(Transport.java:108)
       at io.socket.thread.EventThread.exec(EventThread.java:55)
       at io.socket.engineio.client.Transport.send(Transport.java:103)
       at io.socket.engineio.client.Socket.flush(Socket.java:615)
       at io.socket.engineio.client.Socket.onDrain(Socket.java:606)
       at io.socket.engineio.client.Socket.access$1100(Socket.java:31)
       at io.socket.engineio.client.Socket$6.call(Socket.java:308)
       at io.socket.emitter.Emitter.emit(Emitter.java:117)
       at io.socket.engineio.client.transports.WebSocket$3$1.run(WebSocket.java:171)
       at io.socket.thread.EventThread$2.run(EventThread.java:80)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by mb040574** [comment] 2017-09-20 20:54
On a 64-bit emulator API 25, the problem does not occur...
