### ISSUE TITLE
Socket.IO-client.java disconnect and reconnect repeatedly

### ISSUE THREAD

**Issue by miqe** [socketio/socket.io-client-java#84] opened 2015-01-09 12:05 UTC
I am using  socket.io 1.2.1 on my node server and the android socket connects with the server fine but after some minutes it automatically disconnect and reconnect repeatedly. Whats wrong with my code?
i am using socket.io-client-0.1.1.jar, engine.io-client-0.2.1.jar and Java-WebSocket-1.3.0.jar libraries.
here is the java code

```
    private void socketTest() throws URISyntaxException{
    socket = IO.socket("http://192.168.169.2:8082");
    socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {

      @Override
      public void call(Object... args) {
        socket.emit("test", "awesome");

      }

    }).on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {

      @Override
      public void call(Object... args) {}

    });
    socket.connect();

   }
```

and here is the server side code

```
  io.on('connection', function (socket) {
    console.log('a user connected');
    socket.on('disconnect', function () {
       console.log('user disconnected');
    });
    socket.on('test',function(msg){
       console.log("This is "+msg);
    });
   });
```

and the logs screenshot on the server

![stack](https://cloud.githubusercontent.com/assets/10463154/5679521/7ab53544-97b5-11e4-9a7d-68c585764ad3.png)

[Question link on stackoverflow](http://stackoverflow.com/questions/27860047/socket-io-client-java-disconnect-and-reconnect-repeatedly)

**Comment by drakula84** [comment] 2015-01-16 15:18
I am experiencing the same... any help would be appreciated.

**Comment by nkzawa** [comment] 2015-01-17 09:19
I'd like to know the details.
Does this happen on the latest version? Is it sure that your internet connection is stable?

**Comment by drakula84** [comment] 2015-01-17 17:38
In my case, network connection is fine and I am using this project via @wf9a5m75 's [socket-io cordova plugin] (https://github.com/wf9a5m75/plugin-socket.io) and it seems to link to the latest code base. Thanks..

**Comment by drakula84** [comment] 2015-01-18 00:51
@nkzawa Also, this problem seems to be similar/same as the disconnect/reconnect issue at #60.

**Comment by Miqe** [comment] 2015-01-18 18:28
@nkzawa  i am using socket.io-client-0.1.1.jar, engine.io-client-0.2.1.jar and Java-WebSocket-1.3.0.jar and its on local network, internet should not be the problem.

**Comment by joey0422** [comment] 2015-01-25 11:33
I have the problem when in android phone, too

**Comment by joey0422** [comment] 2015-01-26 07:02
@Miqe Chinese? have email? my email is zy0422_lei@hotmail.com

**Comment by nkzawa** [comment] 2015-01-28 15:14
I tried to reproduce the problem with [a demo app](https://github.com/nkzawa/socket.io-android-chat), but couldn't.

Can you post source code and dump of logs if it's possible?

**Comment by drakula84** [comment] 2015-02-17 19:58
@nkzawa Ok, I tried to the demo app and it disconnects as well.. I cloned both your demo app and example chat.socket.io server source code and ran the server locally and point your demo app to my local server. 

All I do to re-produce is that I just start the client and leave it like that.. after a few mins, it disconnects.  

I added a log statement for disconnect and reconnect on the server side:

```javascript
io.on('connection', function (socket) {
  console.log('a client connected ' + new Date);

  socket.on('disconnect', function () {
    console.log('a client disconnected ' + new Date);
```

Hence logs from server.. 

```javascript
a client connected Tue Feb 17 2015 19:54:37 GMT+0000 (GMT)
a client disconnected Tue Feb 17 2015 19:56:02 GMT+0000 (GMT)
```

Let me know if I can do more to help diagnose the issue.

**Comment by drakula84** [comment] 2015-02-18 01:06
I left the app run itself  without touching the phone at all and here what happens over a while:

```javascript
a client connected Tue Feb 17 2015 19:54:37 GMT+0000 (GMT)
a client disconnected Tue Feb 17 2015 19:56:02 GMT+0000 (GMT)
a client connected Tue Feb 17 2015 20:31:12 GMT+0000 (GMT)
a client disconnected Tue Feb 17 2015 20:32:37 GMT+0000 (GMT)
a client connected Tue Feb 17 2015 20:56:28 GMT+0000 (GMT)
a client disconnected Tue Feb 17 2015 20:57:53 GMT+0000 (GMT)
a client connected Tue Feb 17 2015 21:02:29 GMT+0000 (GMT)
a client disconnected Tue Feb 17 2015 21:03:55 GMT+0000 (GMT)
```

And the client is now aware that it disconnected for a long time (until it actually connects again).. so disconnect event is not fired on the client side when server disconnects happens and log is printed.

**Comment by Yoosuf29** [comment] 2015-04-24 21:14
There is a simple workaround for this, please refer to this: 

https://github.com/nkzawa/socket.io-client.java/issues/123#issuecomment-96066333

**Comment by shuoli84** [comment] 2015-06-24 03:17
@nkzawa Close this?

**Comment by anop72** [comment] 2015-06-24 10:43
@shuoli84 Did you resolve this. I still get problems.

**Comment by shuoli84** [comment] 2015-06-24 14:04
@anop72 0.5.1？

**Comment by anop72** [comment] 2015-06-25 04:42
Yes `compile ('com.github.nkzawa:socket.io-client:0.5.1')`

**Comment by anop72** [comment] 2015-06-25 04:53
@shuoli84 Yes `compile ('com.github.nkzawa:socket.io-client:0.5.1')`

**Comment by shuoli84** [comment] 2015-06-26 03:15
@anop72  I don't have such problem. Share your client code? And also the socketio server's version? And any logs?

**Comment by bwilks128** [comment] 2015-07-09 21:34
Here are my findings on this issue. I have two Android devices: an S3 running Kitkat (4.4.2) and a Tab 4 running Lollipop (5.0.2). Both are running my app using this socket.io client. Only the Tab 4 running Lollipop is affected by this issue.

The Tab 4 disconnects (as detected by the server upon heartbeat timeout) shortly after the Tab 4 goes to sleep while running on battery. The issue will not occur if it is plugged in.

My guess is that in order to continue squeezing better battery life, Lollipop is pausing what appears to be a dormant app and it times out on the server's heartbeat. Kitkat let the app continue to run to some extent if it had an open socket.

To remedy this, I added a wake_lock to my activity that I want to keep running to wait for a connection from a peer. To do this, I added the following to my activity:

private PowerManager.WakeLock wl;

OnCreate

        PowerManager pm = (PowerManager)getApplicationContext().getSystemService(
                Context.POWER_SERVICE);
        this.wl = pm.newWakeLock(
                PowerManager.PARTIAL_WAKE_LOCK
                        | PowerManager.ON_AFTER_RELEASE,
                TAG);
        wl.acquire();

OnDestroy

    wl.release();

After adding this lock, I am no longer having this issue on Lollipop. In thinking about it, Kitkat should probably have paused my app too without a wake_lock but it did not.

Hope this helps.

**Comment by ZhangPeibin** [comment] 2015-07-22 06:41
I met the same problem ........

**Comment by jishuo1213** [comment] 2015-09-02 01:29
@Miqe Do you ues okhttp.jar in you App? I have the same question like you ,my socket disconnect and reconnect repeatedly,when I remove the okhttp.jar , it works well,connect once ,and no disconnect,i dont konw why it like this @nkzawa

**Comment by sandro-csimas** [comment] 2016-02-19 03:16
@bwilks128, do you have a solution for a background service? Class that extends Service.

**Comment by snetts** [comment] 2017-09-19 10:52
Hello guys, I know I am late to the party but I am here anyway. Was this ever resolved, coz its 2017 and I have an app based on Socket.IO and node but there are concerns with battery life and data consumption. If this was resolve could someone direct me to the solution so I can fix my code. Thanks.

**Comment by Jethvasagar** [comment] 2018-03-30 09:21
Just Downgrade the `socket.io-client:0.8.3` version in gradle its work fine for me
 
`compile('io.socket:socket.io-client:0.8.3') {
                    exclude group: 'org.json', module: 'json'
                }`

**Comment by abgmy** [comment] 2018-04-16 17:53
hi @nkzawa & thank you for this nice project.
i think this issue is all about engine:poling, 
if you limit transport to polling,you can see this problem

**Comment by wangxu1989911** [comment] 2018-05-22 00:49
Although it's incredible, for socket.io v1.x, the best java client is 0.8.3 as mentioned by @Jethvasagar .

**Comment by pankajtalaviya97** [comment] 2018-07-27 08:24
Use 0.8.3 version of io.socket remove new version 1.0.0

compile('io.socket:socket.io-client:0.8.3') {
    exclude group: 'org.json', module: 'json'
}

**Comment by ptahchiev** [comment] 2020-01-20 22:20
I've got the same issue. Doesn't work with 1.0.0 nor with 0.8.3 - it keeps disconnecting and reconnecting again :(

**Comment by darrachequesne** [comment] 2021-04-25 21:16
Closed due to inactivity, please reopen if needed.

**Closed by darrachequesne** 2021-04-25 21:16 UTC
Labels: bug

**Comment by WSAyan** [comment] 2021-06-23 12:14
facing the same issue on version **2.0.1**. Server version is **4.1.2**
```
 implementation('io.socket:socket.io-client:2.0.1') {
        exclude group: 'org.json', module: 'json'
    }
```

Client is connecting and disconnecting every 20-25 seconds or so. 
```
I/ChatActivity: 1624449485415 -------> disconnected
I/ChatActivity: 1624449505484 -------> connected
I/ChatActivity: 1624449515496 -------> disconnected
I/ChatActivity: 1624449537038 -------> connected
I/ChatActivity: 1624449561944 -------> disconnected
I/ChatActivity: 1624449582070 -------> connected
I/ChatActivity: 1624449592097 -------> disconnected
I/ChatActivity: 1624449613489 -------> connected
I/ChatActivity: 1624449638581 -------> disconnected
I/ChatActivity: 1624449658677 -------> connected
I/ChatActivity: 1624449668692 -------> disconnected
I/ChatActivity: 1624449689575 -------> connected
I/ChatActivity: 1624449714573 -------> disconnected
I/ChatActivity: 1624449734696 -------> connected
I/ChatActivity: 1624449744714 -------> disconnected
I/ChatActivity: 1624449766331 -------> connected
I/ChatActivity: 1624449791364 -------> disconnected
I/ChatActivity: 1624449811497 -------> connected
I/ChatActivity: 1624449821510 -------> disconnected
I/ChatActivity: 1624449842635 -------> connected
I/ChatActivity: 1624449867651 -------> disconnected
I/ChatActivity: 1624449887725 -------> connected
I/ChatActivity: 1624449897743 -------> disconnected
I/ChatActivity: 1624449918544 -------> connected
I/ChatActivity: 1624449943830 -------> disconnected
I/ChatActivity: 1624449963937 -------> connected
I/ChatActivity: 1624449973954 -------> disconnected
I/ChatActivity: 1624449995551 -------> connected
I/ChatActivity: 1624450020539 -------> disconnected
I/ChatActivity: 1624450040648 -------> connected
I/ChatActivity: 1624450050672 -------> disconnected
I/ChatActivity: 1624450070761 -------> connected
I/ChatActivity: 1624450080781 -------> disconnected
I/ChatActivity: 1624450102100 -------> connected
I/ChatActivity: 1624450127033 -------> disconnected
I/ChatActivity: 1624450147163 -------> connected
I/ChatActivity: 1624450157185 -------> disconnected
I/ChatActivity: 1624450178767 -------> connected
I/ChatActivity: 1624450203808 -------> disconnected
I/ChatActivity: 1624450223906 -------> connected
I/ChatActivity: 1624450233916 -------> disconnected
I/ChatActivity: 1624450255147 -------> connected
I/ChatActivity: 1624450280065 -------> disconnected
I/ChatActivity: 1624450300163 -------> connected
I/ChatActivity: 1624450310176 -------> disconnected
I/ChatActivity: 1624450330883 -------> connected
I/ChatActivity: 1624450355894 -------> disconnected
I/ChatActivity: 1624450376018 -------> connected
I/ChatActivity: 1624450386030 -------> disconnected
I/ChatActivity: 1624450407625 -------> connected
```

**Comment by keshavandroid** [comment] 2021-08-19 13:13
> facing the same issue on version **2.0.1**. Server version is **4.1.2**
> 
> ```
>  implementation('io.socket:socket.io-client:2.0.1') {
>         exclude group: 'org.json', module: 'json'
>     }
> ```
> 
> Client is connecting and disconnecting every 20-25 seconds or so.
> 
> ```
> I/ChatActivity: 1624449485415 -------> disconnected
> I/ChatActivity: 1624449505484 -------> connected
> I/ChatActivity: 1624449515496 -------> disconnected
> I/ChatActivity: 1624449537038 -------> connected
> I/ChatActivity: 1624449561944 -------> disconnected
> I/ChatActivity: 1624449582070 -------> connected
> I/ChatActivity: 1624449592097 -------> disconnected
> I/ChatActivity: 1624449613489 -------> connected
> I/ChatActivity: 1624449638581 -------> disconnected
> I/ChatActivity: 1624449658677 -------> connected
> I/ChatActivity: 1624449668692 -------> disconnected
> I/ChatActivity: 1624449689575 -------> connected
> I/ChatActivity: 1624449714573 -------> disconnected
> I/ChatActivity: 1624449734696 -------> connected
> I/ChatActivity: 1624449744714 -------> disconnected
> I/ChatActivity: 1624449766331 -------> connected
> I/ChatActivity: 1624449791364 -------> disconnected
> I/ChatActivity: 1624449811497 -------> connected
> I/ChatActivity: 1624449821510 -------> disconnected
> I/ChatActivity: 1624449842635 -------> connected
> I/ChatActivity: 1624449867651 -------> disconnected
> I/ChatActivity: 1624449887725 -------> connected
> I/ChatActivity: 1624449897743 -------> disconnected
> I/ChatActivity: 1624449918544 -------> connected
> I/ChatActivity: 1624449943830 -------> disconnected
> I/ChatActivity: 1624449963937 -------> connected
> I/ChatActivity: 1624449973954 -------> disconnected
> I/ChatActivity: 1624449995551 -------> connected
> I/ChatActivity: 1624450020539 -------> disconnected
> I/ChatActivity: 1624450040648 -------> connected
> I/ChatActivity: 1624450050672 -------> disconnected
> I/ChatActivity: 1624450070761 -------> connected
> I/ChatActivity: 1624450080781 -------> disconnected
> I/ChatActivity: 1624450102100 -------> connected
> I/ChatActivity: 1624450127033 -------> disconnected
> I/ChatActivity: 1624450147163 -------> connected
> I/ChatActivity: 1624450157185 -------> disconnected
> I/ChatActivity: 1624450178767 -------> connected
> I/ChatActivity: 1624450203808 -------> disconnected
> I/ChatActivity: 1624450223906 -------> connected
> I/ChatActivity: 1624450233916 -------> disconnected
> I/ChatActivity: 1624450255147 -------> connected
> I/ChatActivity: 1624450280065 -------> disconnected
> I/ChatActivity: 1624450300163 -------> connected
> I/ChatActivity: 1624450310176 -------> disconnected
> I/ChatActivity: 1624450330883 -------> connected
> I/ChatActivity: 1624450355894 -------> disconnected
> I/ChatActivity: 1624450376018 -------> connected
> I/ChatActivity: 1624450386030 -------> disconnected
> I/ChatActivity: 1624450407625 -------> connected
> ```

same problem

**Comment by ramesh998** [comment] 2022-01-28 13:28
If you have any third party chat libraries or any other library that uses socket io internally, remove that code and try again it worked for me.

**Comment by mojojojo42** [comment] 2022-07-24 19:29
> I'd like to know the details. Does this happen on the latest version? Is it sure that your internet connection is stable?

Yes, it's happening in the latest version of `Socket.IO-client Java` [v2.1.0](https://github.com/socketio/socket.io-client-java/releases/tag/socket.io-client-2.1.0)

**Comment by jja08111** [comment] 2023-05-19 02:05
Same issue here

**Comment by dheeraj-su** [comment] 2023-05-19 05:32
@jja08111 Now, it's working for me.

I'm using `'io.socket:socket.io-client:2.1.0'` for the `Android` and also, `Socket.IO` library should be updated on your `server-side`, refer to [Version compatibility](https://socket.io/docs/v4/client-installation/#version-compatibility). I was facing the same issue because of the version mismatch.

I'm sharing my Socket configuration for the Android, please check:
```kotlin
object SocketHandler {

    private val TAG = SocketHandler::class.java.simpleName
    private lateinit var mSocket: Socket

    @Synchronized
    fun setSocket() {
        try {
            val trustManagers =
                TrustManagerFactory
                    .getInstance(TrustManagerFactory.getDefaultAlgorithm())
                    .apply { init(null as KeyStore?) }
                    .trustManagers
            check(!(trustManagers.size != 1 || trustManagers[0] !is X509TrustManager)) {
                ("Unexpected default trust managers: ${Arrays.toString(trustManagers)}")
            }
            val trustManager = trustManagers[0] as X509TrustManager
            val sslContext =
                SSLContext
                    .getInstance("SSL")
                    .apply { init(null, arrayOf(trustManager), null) }
            val okHttpClient =
                with(OkHttpClient.Builder()) {
                    hostnameVerifier { _, _ -> true }
                    sslSocketFactory(sslContext.socketFactory, trustManager)
                    readTimeout(1, TimeUnit.MINUTES) // important for HTTP long-polling
                    if (BuildConfig.DEBUG) {
                        addInterceptor(
                            HttpLoggingInterceptor()
                                .setLevel(HttpLoggingInterceptor.Level.BODY)
                        )
                    }
                    build()
                }
            IO.setDefaultOkHttpWebSocketFactory(okHttpClient)
            IO.setDefaultOkHttpCallFactory(okHttpClient)
            mSocket = IO.socket(BuildConfig.SOCKET_URL, IO.Options.builder().build())
        } catch (e: Exception) {
            e.reportToCrashlytics(
                when (e) {
                    is URISyntaxException -> "INIT_SOCKET"
                    is KeyManagementException,
                    is NoSuchAlgorithmException -> "CONFIG_SSL"
                    else -> "UNKNOWN"
                }, TAG, CrashLogLevel.ERROR
            )
        }
    }

    @Synchronized
    fun getSocket() = mSocket

    @Synchronized
    fun establishConnection() {
        mSocket.connect()
    }

    @Synchronized
    fun closeConnection() {
        mSocket.disconnect()
        mSocket.off()
    }
}
```

**Comment by mojojojo42** [comment] 2023-05-19 05:35
@jja08111 Now, it's working for me.

I'm using `'io.socket:socket.io-client:2.1.0'` for the `Android` and also, `Socket.IO` library should be updated on your `server-side`, refer to [Version compatibility](https://socket.io/docs/v4/client-installation/#version-compatibility). I was facing the same issue because of the version mismatch.

I'm sharing my Socket configuration for the Android, please check:
```kotlin
object SocketHandler {

    private val TAG = SocketHandler::class.java.simpleName
    private lateinit var mSocket: Socket

    @Synchronized
    fun setSocket() {
        try {
            val trustManagers =
                TrustManagerFactory
                    .getInstance(TrustManagerFactory.getDefaultAlgorithm())
                    .apply { init(null as KeyStore?) }
                    .trustManagers
            check(!(trustManagers.size != 1 || trustManagers[0] !is X509TrustManager)) {
                ("Unexpected default trust managers: ${Arrays.toString(trustManagers)}")
            }
            val trustManager = trustManagers[0] as X509TrustManager
            val sslContext =
                SSLContext
                    .getInstance("SSL")
                    .apply { init(null, arrayOf(trustManager), null) }
            val okHttpClient =
                with(OkHttpClient.Builder()) {
                    hostnameVerifier { _, _ -> true }
                    sslSocketFactory(sslContext.socketFactory, trustManager)
                    readTimeout(1, TimeUnit.MINUTES) // important for HTTP long-polling
                    if (BuildConfig.DEBUG) {
                        addInterceptor(
                            HttpLoggingInterceptor()
                                .setLevel(HttpLoggingInterceptor.Level.BODY)
                        )
                    }
                    build()
                }
            IO.setDefaultOkHttpWebSocketFactory(okHttpClient)
            IO.setDefaultOkHttpCallFactory(okHttpClient)
            mSocket = IO.socket(BuildConfig.SOCKET_URL, IO.Options.builder().build())
        } catch (e: Exception) {
            e.reportToCrashlytics(
                when (e) {
                    is URISyntaxException -> "INIT_SOCKET"
                    is KeyManagementException,
                    is NoSuchAlgorithmException -> "CONFIG_SSL"
                    else -> "UNKNOWN"
                }, TAG, CrashLogLevel.ERROR
            )
        }
    }

    @Synchronized
    fun getSocket() = mSocket

    @Synchronized
    fun establishConnection() {
        mSocket.connect()
    }

    @Synchronized
    fun closeConnection() {
        mSocket.disconnect()
        mSocket.off()
    }
}
```
