### ISSUE TITLE
latency in receiving socket.on message on android client

### ISSUE THREAD

**Issue by laspero** [socketio/socket.io-client-java#272] opened 2016-01-14 14:52 UTC
I am sending an echo request from a node server to the android client and it takes 50ms to 150ms for the android client to receive the message.  When I initiate a echo request from the android client to the server I can get a round trip emit and ack in under 6ms consistently.  The same setup using angular on chrome browser responds to the server in under 3ms.  Is there some configuration setting in this library that would decrease the latency to messages sent to the android client or is this something inherit to the protocol on android devices?

**Comment by nkzawa** [comment] 2016-01-16 05:22
It sounds duplicate of https://github.com/socketio/socket.io-client-java/issues/262

**Closed by nkzawa** 2016-01-16 05:22 UTC

**Comment by chelinho139** [comment] 2016-01-29 06:29
its happening to us too, its almost double the time it takes compared to desktop.
