### ISSUE TITLE
Nullpointer in .call in 0.8.0 version

### ISSUE THREAD

**Issue by eckovation** [socketio/socket.io-client-java#344] opened 2016-09-25 09:05 UTC
How should we handle this error?

Fatal Exception: java.lang.NullPointerException
       at io.socket.engineio.client.Socket$7.call(Socket.java:346)
       at io.socket.emitter.Emitter$OnceListener.call(Emitter.java:164)
       at io.socket.emitter.Emitter.emit(Emitter.java:117)
       at io.socket.engineio.client.Transport.onOpen(Transport.java:122)
       at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:28)
       at io.socket.engineio.client.transports.WebSocket$2$1.run(WebSocket.java:93)
       at io.socket.thread.EventThread$2.run(EventThread.java:80)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

**Comment by nkzawa** [comment] 2016-09-25 09:15
duplicate of https://github.com/socketio/socket.io-client-java/issues/343

**Closed by nkzawa** 2016-09-25 09:15 UTC
