### ISSUE TITLE
still frequently reconnection in my first connection， wait on line...., my log is here

### ISSUE THREAD

**Issue by hpustudent** [socketio/socket.io-client-java#229] opened 2015-10-18 13:59 UTC
my server is node.js+socket.io ，the version of socket.io is 1.x，the problem is stil alive，my app is about to on the line , is anyone know the other way to connect to socke.io server? 

this is my log:
![3](https://cloud.githubusercontent.com/assets/11389849/10572350/397d8294-767a-11e5-9a1e-484fed209a76.png)

transport is always "polling"

can I contact to you with IM  so that i can support you more infomation?

**Comment by nkzawa** [comment] 2015-10-20 01:28
Do you mean having the same problem before too? Can you post your code?
Regarding WebSocket connection, it can fail for many reasons. So I recommend to check whether bare WebSocket works fine or not.

**Comment by hpustudent** [comment] 2015-10-20 02:05
@nkzawa  our app contains ios and android , the ios version works well and the socket.io module is supported by socket.io official, if it is possible , you can remote control my computer for solving the problem,  here is my code , i will online to wait you thanks:
![1](https://cloud.githubusercontent.com/assets/11389849/10596044/ff0d69a6-7711-11e5-8fab-64a790499e13.png)
![2](https://cloud.githubusercontent.com/assets/11389849/10596046/0546734e-7712-11e5-8df5-9169fa2e6d39.png)
![3](https://cloud.githubusercontent.com/assets/11389849/10596053/0b4f7dee-7712-11e5-88dc-18ad46e9fd88.png)
![4](https://cloud.githubusercontent.com/assets/11389849/10596056/0f1593f0-7712-11e5-8e0c-1a195c1d6e5d.png)

**Comment by nkzawa** [comment] 2015-10-20 02:22
Unfortunately, I can't help you like that. Your code looks OK. Do you know how we can reproduce the issue? Any other detailed logs?

**Comment by hpustudent** [comment] 2015-10-20 02:35
my android app runs on 300 mechine for testing，they always encounter the problem in any time.
the more log details after previous:
![log2](https://cloud.githubusercontent.com/assets/11389849/10596306/881d8142-7715-11e5-85d6-7fec6c4efec6.png)
![log3](https://cloud.githubusercontent.com/assets/11389849/10596310/8e439926-7715-11e5-87c3-e22f930ebf70.png)

**Comment by hpustudent** [comment] 2015-10-20 02:53
I just bought a server, I will build a test environment as soon as possible, and then tell you the account and password, in order to reproduce the bug。

**Comment by nkzawa** [comment] 2015-10-20 03:14
Thanks for the logs, but still I have no idea.

Can you modify the source code of engine.io-client-java, and debug what kind of errors actually happen in the following methods?

https://github.com/socketio/engine.io-client-java/blob/master/src/main/java/io/socket/engineio/client/transports/PollingXHR.java#L250
https://github.com/socketio/engine.io-client-java/blob/master/src/main/java/io/socket/engineio/client/transports/WebSocket.java#L134

**Comment by hpustudent** [comment] 2015-10-20 03:28
![Uploading 1.png…]()

**Comment by hpustudent** [comment] 2015-10-20 03:37
![8](https://cloud.githubusercontent.com/assets/11389849/10597213/f9c9b622-771e-11e5-8d52-6670eb272d92.png)

**Comment by hpustudent** [comment] 2015-10-20 05:56
I already update the logs ,please see the post above.

**Comment by hpustudent** [comment] 2015-10-21 02:45
@nkzawa  It seems the error is caused by okHttp, https://github.com/square/okhttp/issues/1114

**Comment by nkzawa** [comment] 2015-10-21 22:55
@hpustudent sorry for the delay. looks like so. Does `android:vmSafeMode: true` work for you?

**Comment by hpustudent** [comment] 2015-10-22 01:11
The problem is still alive，but why can't the websocket transport build?

**Comment by nkzawa** [comment] 2015-10-22 06:31
What version of socket.io-client-java do you use? Can you test with the latest version if you are using an old version, since they say `okio` was fixed on 1.6.0.

https://github.com/square/okhttp/issues/1518

**Comment by hpustudent** [comment] 2015-10-22 06:37
It is really the latest version , okio version :1.6.0 , okhttp: 2.5.0

**Comment by sandro-csimas** [comment] 2016-02-18 15:18
+1. The same here!
````
2016-02-18T15:15:36.526Z - debug: User 1 disconnected (Socket Ll0f9KVDB3s3L55mAC_o)
2016-02-18T15:15:40.560Z - debug: User 1 connected (Socket 1M2io37tnb3q8mfoADAC)
2016-02-18T15:16:41.788Z - debug: User 1 disconnected (Socket 1M2io37tnb3q8mfoADAC)
2016-02-18T15:16:49.348Z - debug: User 1 connected (Socket pikX83RthVZBtPSGADAW)
2016-02-18T15:17:50.813Z - debug: User 1 disconnected (Socket pikX83RthVZBtPSGADAW)
2016-02-18T15:17:54.487Z - debug: User 1 connected (Socket 9sT9iiDiP8NiAaHTADAq)
````

**Comment by shobhitpuri** [comment] 2016-08-02 18:06
Is there a solution for this?

**Comment by darrachequesne** [comment] 2021-04-25 21:37
Closed due to inactivity, please reopen if needed.

**Closed by darrachequesne** 2021-04-25 21:37 UTC
