### ISSUE TITLE
Consistent XHR Post Error

### ISSUE THREAD

**Issue by vjaros2** [socketio/socket.io-client-java#241] opened 2015-11-04 02:46 UTC
I've been trying to use this library (version 0.6.2) to connect to a SocketIO server and emit a few events from my Android app. However, I can't seem to emit anything without getting the following:

`An error ocurred: io.socket.engineio.client.EngineIOException: xhr post error`

I've been trying to resolve this for a few days. I've made sure that I have the necessary internet permissions, an internet connection, etc. Despite all this, I've made no progress in debugging whatever is wrong.

Here are the pertinent portions of my implementation:

```
// ...
// imports
// ...

public class MessageActivity extends Activity {

    private Socket mSocket;
    {
        try {
            mSocket = IO.socket("http://my-server.rhcloud.com/namespace");
        } catch (URISyntaxException e) {
            // handle error
        }
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        mSocket.on("error", new Emitter.Listener() {
            @Override
            public void call(final Object... args) {
                String error = args[0].toString();
                // handle error
            }
        }).on("connect", new Emitter.Listener() {
            @Override
            public void call(final Object... args) {
                JSONObject data= new JSONObject("{\"test\": true}");
                mSocket.emit("event", data);
            }
        });
        mSocket.connect();

        // ...
        // set layout, add UI handlers, etc.
        // ...
   }
}
```

Any assistance that you can provide is greatly appreciated.

**Comment by denebasecas** [comment] 2015-11-05 01:25
The same error here. I'm using this:
- ANDROID: library (version 0.6.2
- WEB: library version 1.0.6


I'll paste my code, maybe it would help to identify the problem.

Please (God sake XD), someone have to know the answer... 

```Java
//SERVICE
public class ChatService extends Service {
    public MySocket mSocket;

    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        mSocket = new MySocket(null, null);
        Log.v("DENEB", "DENEB - Servicio CREADO");
        mSocket.connect();
        return START_STICKY;
    }
}
```

```Java
// SOCKET

public class MySocket {
    private static Socket socket;
    private Activity mActivity;
    private Fragment mFragment;

    public MySocket(Activity activity, Fragment fragment) {
        mActivity = activity;
        mFragment = fragment;

        if (socket == null) {
            create();
        }
    }


    private synchronized static Socket create() {
        try {
           // I put IP:PORT to hide the real URI in the question
            socket = IO.socket("http://IP:PORT");

            socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Log.v("DENEB", "LOG- connect "+ args[0].toString());
                }

            }).on(Socket.EVENT_CONNECT_ERROR, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Log.v("DENEB", "LOG-connect error: "+ args[0].toString());
                }

            })
           ....
           // more code
           ...
            ;
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }

        return socket;
    }

    public Socket getSocket() {   return socket;   }

    public void connect() {   socket.connect();   }

    public void disconnect() {   socket.disconnect();  }

}

```

**Comment by nmagerko** [comment] 2015-11-05 03:29
+1

**Comment by oliverhausler** [comment] 2015-11-07 21:17
Same here. I've been following this for long, and I do not believe your code is the problem.

What I can say:

- It was better with the 0.5.1 (or 0.5.2, don't remember) client version and okhttp 2.4.0.
- It seems to happen more frequently on devices SDK 17 and under, but it also happens on newer devices. And it happens without a network issue being present as it seems.
- When a disconnect/error occurs, ioOptions.reconnectionDelay is not honored, instead, the connection only times out after reconnectionMaxDelay, and then the reconnect occurs.

**Comment by nkzawa** [comment] 2015-11-09 19:09
Does this mean you can't connect sockets at all? Your code looks good to me.

**Comment by vjaros2** [comment] 2015-11-09 19:22
I am able to connect, as the EVENT_CONNECT Listener is triggered. However, when I attempt to emit an event ("join") that is defined on the server, I encounter an XHR Post Error each time. I've confirmed a correct server URL and  server-side functionality with a JS webapp.

**Comment by nkzawa** [comment] 2015-11-09 19:31
Do you know how we can reproduce? Can you try [demo app](https://github.com/nkzawa/socket.io-android-chat) if it works for you?

**Comment by vjaros2** [comment] 2015-11-10 01:10
The demo app works beautifully, but I'm not sure how I can help you reproduce the error. It seems to me like the predefined constants (like connect) in the library are sent out properly, but custom events are not always handled properly. (like a "join" emit for example) They just never make it off my phone.

**Comment by nkzawa** [comment] 2015-11-10 01:57
Umm, it seems rather your app or server is wrong if demo app works fine. Can you post logs of the library if possible? You can enable it like this http://stackoverflow.com/questions/4561345/how-to-configure-java-util-logging-on-android .

**Comment by oliverhausler** [comment] 2015-11-10 03:12
As it looks, xhr poll error is triggered by io.socket.engineio.client.transports.PollingXHR.java.

Normally, PollingXHR is initialized on multiple threads within short time intervals. These "parallel" requests are then executed against the server.

Normally, these requests are returned (or fail) in order, and a disconnected socket is reconnected if at least one of these parallel requests returns 200 OK. As long as an error is returned, the socket stays disconnected.

If a race condition occurs, and the socket is reconnected, but then an earlier request returns an error, xhr poll error is returned and the successfully connected socket is disconnected.

around ln 220:

                        final int statusCode = xhr.getResponseCode();
                        if (HttpURLConnection.HTTP_OK == statusCode) {
                            self.onLoad();
                        } else {
                            self.onError(new IOException(Integer.toString(statusCode))); // [A]
                        }
                    } catch (IOException e) {
                        self.onError(e); // [B]
                    } catch (NullPointerException e) {
                        // It would occur to disconnect
                        // https://code.google.com/p/android/issues/detail?id=76592
                        self.onError(e);
                    } finally {
                        try {
                            if (output != null) output.close();
                        } catch (IOException e) {}
                    }

In case [A], we have the situation where the server responded with an error, in case [B] we have the situation, where (for whatever reason) the server couldn't be reached and a timeout occurs.

To prevent this error, the receiver of the event would need to look into the reason for the IOException, and if it would determine a timeout has occurred [if it can do this as both are IOExceptions with just a description], instead of throwing "xhr poll error" and disconnecting the socket, it should first check if the socket is already connected, and in this case swallow and ignore the timeout of any parallel thread (because the socket is connected already).

[This here is a speculation and I am still investigating into this.]

**Comment by oliverhausler** [comment] 2015-11-10 03:28
under [B], I am also seeing:

- Connection closed by peer (when using SSL)
- EHOSTUNREACH (No route to host)

**Comment by vjaros2** [comment] 2015-11-10 05:06
My complete error log: http://pastebin.com/dScUBDjU

**Comment by oliverhausler** [comment] 2015-11-10 16:06
@vjaros2 oops, I just looked at your stack trace and realized we are having a different issue. I have the issue during doPoll, not doWrite. There is a "xhr post error" and "xhr poll error". My bad, I overlooked this.

**Comment by nkzawa** [comment] 2015-11-11 05:15
@vjaros2 thanks for the log, but still I have no idea..

**Comment by nkzawa** [comment] 2015-11-11 05:17
@denebasecas I think that's because socket.io version is too old on server. Please update it to newer one.

**Comment by nkzawa** [comment] 2015-12-23 07:03
Closed due to inactivity. Feel free to reopen. If your socket.io is an old version, please update.

**Closed by nkzawa** 2015-12-23 07:03 UTC

**Comment by aliiizzz** [comment] 2017-07-05 19:42
i have same error, but when i move app to http everything works fine. the problem i think is https.
i tried to trust all certificates but it doesn't work

**Comment by deviant-studio** [comment] 2017-11-21 13:55
same issue. it occurs on some specific android devices

**Comment by ramkrishnagalla** [comment] 2018-03-21 17:34
Any body solved this .. Same error when I m trying connect to https .. even added trust all.
