### ISSUE TITLE
data loss

### ISSUE THREAD

**Issue by eggham0518** [socketio/socket.io-client-java#620] opened 2020-07-10 07:46 UTC
I think there is a loss on the byte array when I receive it. 
When sent from Android, all the data was sent properly.

`        
           
           JSONObject msgObject = new JSONObject();

            byte[] convertedImg = readFileToByteArray(imgFile);

            msgObject.put(token, this.token);

            msgObject.put(img, convertedImg);   

        mSocket.emit(send_img, msgObject);`

rawData:: {
      "nameValuePairs": {
        "sender_idx": 35656,
        "nickname": "teemo",
        "img": [
          -1,
          -40,
          -1,
          -32,
          0,
          16,
          74,
          70,
          73,
          70,
          0,
          1,
          1,
          0,
          0,
          1,
          0,
          1,
          0,
          0,
          -1,
          -30,
          2,
          28,
          73,
          67,
          67,
          95,
          80,
          82,
          79,
          70,
          73,
          76,
          69,
          0,
          1,
          1,
          0,
          0,
          2,
          12,
          108,
          99,
          109,
          115,
          2,
          16,
          0,
          0,
          109,
          110,
          116,
          114,
          82,
          71,
          66,
          32,
          88,
          89,
          90,
          32,
          7,
          -36,
          0,
          1,
          0,
          25,
          0,
          3,
          0,
          41,
          0,
          57,
          97,
          99,
          115,
          112,
          65,
          80,
          80,
          76,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          -10,
          -42,
          0,
          1,
          0,
          0,
          0,
          0,
          -45,
          45,
          108,
          99,
          109,
          115,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          10,
          100,
          101,
          115,
          99,
          0,
          0,
          0,
          -4,
          0,
          0,
          0,
          94,
          99,
          112,
          114,
          116,
          0,
          0,
          1,
          92,
          0,
          0,
          0,
          11,
          119,
          116,
          112,
          116,
          0,
          0,
          1,
          104,
          0,
          0,
          0,
          20,
          98,
          107,
          112,
          116,
          0,
          0,
          1,
          124,
          0,
          0,
          0,
          20,
          114,
          88,
          89,
          90,
          0,
          0,
          1,
          -112,
          0,
          0,
          0,
          20,
          103,
          88,
          89,
          90,
          0,
          0,
          1,
          -92,
          0,
          0,
          0,
          20,
          98,
          88,
          89,
          90,
          0,
          0,
          1,
          -72,
          0,
          0,
          0,
          20,
          114,
          84,
          82,
          67,
          0,
          0,
          1,
          -52,
          0,
          0,
          0,
          64,
          103,
          84,
          82,
          67,
          0,
          0,
          1,
          -52,
          0,
          0,
          0,
          64,
          98,
          84,
          82,
          67,
          0,
          0,
          1,
          -52,
          0,
          0,
          0,
          64,
          100,
          101,
          115,
          99,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          3,
          99,
          50,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          116,
          101,
          120,
          116,
          0,
          0,
          0,
          0,
          70,
          66,
          0,
          0,
          88,
          89,
          90,
          32,
          0,
          0,
          0,
          0,
          0,
          0,
          -10,
          -42,
          0,
          1,
          0,
          0,
          0,
          0,
          -45,
          45
          
`

**Comment by bbulkow** [comment] 2021-02-27 22:50
Hi, there's no way this can be debugged by people who maintain the code. Printing the entire array doesn't help. Can you please close the issue or provide enough information to reproduce the issue?

**Comment by darrachequesne** [comment] 2021-04-26 22:19
Closed due to inactivity, please reopen if needed.

**Closed by darrachequesne** 2021-04-26 22:19 UTC
