### ISSUE TITLE
Hey Just a suggestion

### ISSUE THREAD

**Issue by guptaamol** [socketio/socket.io-client-java#444] opened 2017-07-29 20:26 UTC
if only you could provide access to send and receive buffer in the socket class.

So there can be implementation made in on-disconnect to clear the buffer, store it locally and then emit it back at a later stage to provide a manual implementation to avoid failures or re-emitting in case of internet loss.

**Comment by darrachequesne** [comment] 2022-06-30 06:04
Duplicate of https://github.com/socketio/socket.io-client-java/issues/412.

**Closed by darrachequesne** 2022-06-30 06:04 UTC
