### ISSUE TITLE
socket io disconnected, but the client didn't know

### ISSUE THREAD

**Issue by joy-jianqiang** [socketio/socket.io-client-java#197] opened 2015-08-14 10:24 UTC
if the screen is locked more than 15 minutes, the server side found the socket.io is disconnect, but the client side would not found it, i receive ACTION_TIME_TICK in app, and log out the socket status, it always return true with mSocket.connected(), is there a solution?
sorry for bad English

**Comment by wedneyyuri** [comment] 2015-08-14 11:10
@joy-jianqiang Are you using [partial wake lock](http://developer.android.com/reference/android/os/PowerManager.html#PARTIAL_WAKE_LOCK)?

**Comment by wedneyyuri** [comment] 2015-08-14 11:11
Possible duplicate of  #84

**Comment by joy-jianqiang** [comment] 2015-08-15 01:48
@wedneyyuri  I didn't use a partial wake lock， i will try it, but in hope my app can receive the chat message when the app is in background， seems i do not how to use the partial exactly.
And thanks for advice.

**Closed** 2017-12-04 11:52 UTC
