### ISSUE TITLE
java.net.MalformedURLException: Unknown protocol: ws

### ISSUE THREAD

**Issue by Zo2m4bie** [socketio/socket.io-client-java#233] opened 2015-10-22 09:32 UTC
Hi. i try to connect to socket server which start with "ws://..." and when I set this url to 

```
 IO.socket(pathSocket, options);
```

I receive error

```
 java.lang.RuntimeException: java.net.MalformedURLException: Unknown protocol: ws
 W/System.err﹕ at io.socket.client.Url.parse(Url.java:52)
 W/System.err﹕ at io.socket.client.IO.socket(IO.java:60)
 W/System.err﹕ at io.socket.client.IO.socket(IO.java:41)
```

**Comment by nkzawa** [comment] 2015-10-22 09:52
Ah, I didn't know `URL` doesn't accept `ws`. It's a bug, please use `http://` url for now.

**Comment by Zo2m4bie** [comment] 2015-10-22 10:50
Also the same problem with wss://

**Comment by Zo2m4bie** [comment] 2015-10-22 14:19
Can I wait this fix soon?

**Comment by Zo2m4bie** [comment] 2015-10-22 14:40
I wanted t ofix it by myself but there're not all class in project

**Comment by nkzawa** [comment] 2015-10-22 14:46
Just use `http://` or `https://`. They are actually the same with `ws://` and `wss://` .

**Comment by SteveMobile** [comment] 2015-12-30 12:25
we use the websocket can connect wss:// , but use this library ,can't connect the "https://" , no any reponse,can you help ?

**Comment by PuKoren** [comment] 2016-03-16 15:56
+1, this is causing heavy issues on socket servers: losing a lot of CPU on back and forth requests upgrading the connexion. This is a major issue when having 10k connection/second

**Comment by kruyvanna** [comment] 2016-07-27 15:28
+1

**Comment by sindrenm** [comment] 2016-10-12 07:36
This is caused by java.net.URL not knowing how to open a connection towards a `ws://` stream. It could be solved by using java.net.URI instead, which is what the [Java-WebSocket library uses][uri].

[uri]: https://github.com/TooTallNate/Java-WebSocket/blob/58d17786958ec2b629b75de1eed00915b3e4f7c4/src/main/java/org/java_websocket/client/WebSocketClient.java#L37

**Comment by sr71k** [comment] 2016-11-03 08:12
did  it  fix?

**Comment by Agraphie** [comment] 2016-12-08 10:08
are there any news on this?

**Comment by b95505017** [comment] 2016-12-09 09:38
Maybe we could use this to resolve the issue
https://medium.com/square-corner-blog/okhttps-new-url-class-515460eea661#.v55accs1c

**Comment by jvilya** [comment] 2017-02-07 04:42
We are using Socket.io 1.5 and this library on Android client. For connection string we are using http(s), but it switches to ws automatically with these setup:

```java
    IO.Options opts = new IO.Options();
    opts.transports = new String[]{ WebSocket.NAME};
    return IO.socket("https://socket.io.server", opts);
```

**Comment by isanwenyu** [comment] 2017-07-30 14:01
@jvilya hi,I can't find the 1.4.5 release version in this repo.I  have tried your code above,but it doesn't work.
Could you tell me details,please.

**Comment by jvilya** [comment] 2017-07-31 02:34
@isanwenyu yes. Try to debug it with any proxy-debugging tool and see what happens
In my case I saw  connection to `https` and then switch to `ws`

**Comment by nuttyboysoftware** [comment] 2017-10-17 09:23
2 Years later and still no fix? is this product no longer being supported?

**Comment by maheshputtegowda1990** [comment] 2018-03-04 06:52
hello guys this ws: issue is fixed?

**Comment by maheshputtegowda1990** [comment] 2018-03-04 06:52
any solution to implement

**Comment by GirishBhutiya** [comment] 2018-05-01 12:56
Still not working and it is not connect with http:// .

**Comment by Kiplol** [comment] 2018-06-06 20:06
I'm having this issue as well, blocking development of a feature for our Android app.

**Comment by PhonegapProjects** [comment] 2018-08-16 11:01
not working at all!!!!!!!!!

**Comment by jakubzieba** [comment] 2019-03-27 13:16
after a year ... it still does not work

**Comment by songkadi** [comment] 2019-04-12 04:57
no hope for this topic

**Comment by tiholic** [comment] 2019-08-11 08:14
https://github.com/infitio/flutter_socket_io/issues/34

**Comment by Arnique** [comment] 2019-12-07 19:46
The socket server I'm connecting to only works with wss...any solutions for 2019?

**Comment by xiaoshengmm** [comment] 2019-12-13 05:28
java.lang.RuntimeException: java.net.MalformedURLException: Unknown protocol: ws   who know？how to fix it

**Comment by rogerthat94** [comment] 2019-12-18 17:38
> Maybe we could use this to resolve the issue
> https://medium.com/square-corner-blog/okhttps-new-url-class-515460eea661#.v55accs1c

This doesn't fix the ws: issue. OkHttp just replaces ws: with http: before parsing the URL.

**Comment by felipecsl** [comment] 2020-02-29 19:15
from the `HttpUrl` javadocs:
```
 * Sometimes referred to as *protocol*, A URL's scheme describes what mechanism should be used to
 * retrieve the resource. Although URLs have many schemes (`mailto`, `file`, `ftp`), this class only
 * supports `http` and `https`. Use [java.net.URI][URI] for URLs with arbitrary schemes.
```

**Comment by H4kt** [comment] 2020-04-06 11:47
Idk if someone is still looking for an easy hot-fix, but I'll just leave it here.
`
    public static void addURLProtocols() {

        try {

            Field field = URL.class.getDeclaredField("handlers");
            field.setAccessible(true);

            URLStreamHandler handler = new URLStreamHandler() {
                @Override
                protected URLConnection openConnection(URL url) throws IOException {
                    return new URLConnection(url) {
                        @Override
                        public void connect() throws IOException {}
                    };
                }
            };

            Hashtable<String, URLStreamHandler> handlers = (Hashtable<String, URLStreamHandler>) field.get(null);
            handlers.put("wss", handler);
            handlers.put("ws", handler);

        } catch(Exception ex) {
            ex.printStackTrace();
        }

    }
`

**Comment by vasilevungureanu** [comment] 2020-07-28 07:04
Hi,

I was able to solve this problem in this way:

`
 val options = IO.Options()
            options.forceNew = true
            options.path = "/wss"

 socket = IO.socket("https://", options)
           
`

**Comment by Mohamed-Shalabi** [comment] 2020-09-15 08:37
Nothing here is working for me..
I have used org.java_websocket and it worked well, but I need to know what is the problem with socket io!

**Comment by H4kt** [comment] 2020-10-28 19:56
@Mohamed-Shalabi 
Have you tried the code below?

> Idk if someone is still looking for an easy hot-fix, but I'll just leave it here.
> 
> ```
>     public static void addURLProtocols() {
> 
>         try {
> 
>             Field field = URL.class.getDeclaredField("handlers");
>             field.setAccessible(true);
> 
>             URLStreamHandler handler = new URLStreamHandler() {
>                 @Override
>                 protected URLConnection openConnection(URL url) throws IOException {
>                     return new URLConnection(url) {
>                         @Override
>                         public void connect() throws IOException {}
>                     };
>                 }
>             };
> 
>             Hashtable<String, URLStreamHandler> handlers = (Hashtable<String, URLStreamHandler>) field.get(null);
>             handlers.put("wss", handler);
>             handlers.put("ws", handler);
> 
>         } catch(Exception ex) {
>             ex.printStackTrace();
>         }
> 
>     }
> ```

**Comment by darrachequesne** [comment] 2021-04-27 08:50
For future readers: this should be fixed by https://github.com/socketio/socket.io-client-java/commit/67fd5f34a31c63f7884f82ab39386ad343527590, included in version `2.0.1`.

**Closed by darrachequesne** 2021-04-27 08:50 UTC
Labels: bug

**Comment by TheFoLLoNeRoU** [comment] 2022-01-12 16:35
> For future readers: this should be fixed by [67fd5f3](https://github.com/socketio/socket.io-client-java/commit/67fd5f34a31c63f7884f82ab39386ad343527590), included in version `2.0.1`.

Thank you very mach!! I was using version very old and i was founding very problems with exception about "ws" and problems of connected to server with protocol "http"
