### ISSUE TITLE
0.6.3: Android with Proguard build: SimException: CstInterfaceMethodRef cannot be cast to CstMethodRef

### ISSUE THREAD

**Issue by ywan133** [socketio/socket.io-client-java#270] opened 2016-01-13 02:06 UTC
After updating to 0.6.3 (0.6.2 works fine):

My environment,
Android Studio: 1.5.1 (also tested on 2.0 Preview 4)
Gradle version: 2.10
Android Plugin Version 1.5.0

tested if with '-dontobfuscate', works no problem, but I really want obfuscation enabled...

Error Message:

:app:transformClassesWithDexForRelease
Uncaught translation error: com.android.dx.cf.code.SimException: com.android.dx.rop.cst.CstInterfaceMethodRef cannot be cast to com.android.dx.rop.cst.CstMethodRef
1 error; aborting

 FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:transformClassesWithDexForRelease'.
  
  > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by nkzawa** [comment] 2016-01-16 05:35
duplicate of https://github.com/socketio/socket.io-client-java/issues/225. I think this is the problem of Proguard anyway.

**Comment by beeK99** [comment] 2016-02-25 12:16
I am getting same problem in my proguard or build.gradle

Please let me know how you did if you got success

**Comment by bbfxier** [comment] 2017-09-28 12:06
i got the same error, do you find a way to sovle? thx

**Comment by darrachequesne** [comment] 2021-04-25 21:54
Closed due to inactivity, please reopen if needed.

**Closed by darrachequesne** 2021-04-25 21:54 UTC
